#!/usr/bin/env bash

set -e

echo "Building frontend"
npx webpack --config webpack.prod.js

echo "Building backend"
cargo build --release

echo "Done, FE builds in dist/, BE builds in otemot/target/release/"
