#!/usr/bin/env bash

set -e

echo "Building frontend"
T_ENV=production npx webpack --config ui/webpack.config.js

echo "Building backend"
cd aph; mix release

echo "Done, FE builds in dist/, BE builds in aph/_build/prod/"
