#!/usr/bin/env bash

set -e

echo "Building frontend"
npx webpack --config ui/webpack.prod.js

echo "Building backend"
cd aph; mix release

echo "Done, FE builds in dist/, BE builds in aph/_build/prod/"
