#!/usr/bin/env bash

set -e

# Convenience script for performing a release.

if [ -z "$1" ]
then
	echo "Please input a version string!"
	exit 1
fi

if [ -z "$2" ]
then
	echo "Please input an architecture name!"
	echo "You can get this from running 'rustup show active-toolchain'."
	echo "For example, x86_64-unknown-linux-gnu"
	exit 1
fi

echo "Building..."
script/build
echo "Archiving..."
mkdir tometo
cp target/release/otemot tometo/server
cp -r dist/ tometo/client
cp config.example.toml tometo/config.toml
tar czf "tometo-$1-$2.tar.gz" tometo/
rm -r tometo
echo "Creating directory and moving archive..."
mkdir -p "releases/$1/"
mv "tometo-$1-$2.tar.gz" "releases/$1/"
echo "Attempting to sign..."
minisign -Sm "releases/$1/tometo-$1-$2.tar.gz" -x "releases/$1/tometo-$1-$2.tar.gz.minisig"

echo "All done! You can build for other architectures, or create a Git tag and release."
