#!/usr/bin/env bash

if [[ "$*" == "vagrant" ]]
then
    npx webpack-dev-server --config ui/webpack.config.js --disable-host-check --host 0.0.0.0 --useLocalIp
else
    npx webpack-dev-server --config ui/webpack.config.js
fi
