#!/usr/bin/env bash


if [[ "$*" == "vagrant" ]]
then
    npx concurrently -n "f,b" "npx webpack-dev-server --config ui/webpack.dev.vagrant.js" "cd aph; mix phx.server"
else
    npx concurrently -n "f,b" "npx webpack-dev-server --config ui/webpack.dev.js" "cd aph; mix phx.server"
fi